### ISSUE TITLE
CI tests started to fail for py3.6

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#168]
**Description**
Please see these [CI checks](https://github.com/NCAR/geocat-comp/actions/runs/1067932955) to see Ubuntu and macos tests fail for python 3.6 on `main` branch.

@anissa111 @hCraker @pilotchute I have assigned all of you just to leave it to you who actually would fix it.

**Comment by hCraker** [comment]
All of the errors are the same (shown below)
```
E     File "/usr/local/miniconda/envs/geocat_comp_build/lib/python3.6/site-packages/xarray/core/computation.py", line 4
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
```

This is a [future statement](https://docs.python.org/3/reference/simple_stmts.html#future) which tells the compiler that a module should be compiled using semantics that will be available in a later release of Python. `annotations` is a [future feature](https://docs.python.org/3/library/__future__.html) that is only supported in Python 3.7.0 and beyond. Since xarray is now incorporating this statement in preparation for later Python releases, it no longer supports Python 3.6.

I'm not sure why this is breaking now, because according to the [release notes](http://xarray.pydata.org/en/stable/whats-new.html#v0-17-0-24-feb-2021) xarray 0.17.0 stopped supporting python 3.6 and xarray has moved through 4 version bumps since then. In short, we can no longer support Python 3.6 unless we rollback to using an older version of xarray.

**Comment by anissa111** [comment]
I'm okay with dropping support for python 3.6. I believe we've considered it before when something else conflicted. 

My personal choice would be to use the newest versions of xarray and drop 3.6 support, what does everybody else think @erogluorhan @pilotchute @michaelavs?

**Comment by erogluorhan** [comment]
I am fine with stopping our py3.6 support
