### ISSUE TITLE
Weighted correlation funtion

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-comp#229]
**Describe the feature you'd like added to this project**
A user requested functionality for weighted correlation along with weighted standard deviation, variance, sum, and mean. This issues addresses only the weighted correlation request. 

**Links to other examples, if applicable**
[Scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html) has an unweighted 1D version for array like objects
[xskillscore](https://xskillscore.readthedocs.io/en/stable/api/xskillscore.pearson_r.html#xskillscore.pearson_r) has a weighted N dimensional version that only supports `xarray.Dataset` and `xarray.DataArray`

**Describe the solution you'd like**
The function should support `xarray.Dataset`, `xarray.DataArray`, as well as `numpy.ndarray`. For multidimensional data, there should be a way to specify what dimension to apply the correlation along, otherwise the correlation is done across all dimensions.

**Comment by hCraker** [comment]
@NCAR/geocat [xskillscore.pearson_r]() does all of what the user requested in what appears to be linear time. We already have quite a few dependencies for geocat-comp. Would anyone be opposed to adding another one?

Pros:
- including xskillscore avoids duplicating effort
- faster implementation for this user request
- function already has great documentation with an example

Cons:
- adding a 10th dependency for our package
- `pearson_r` doesn't have support for `numpy.ndarray`
- may run into issues if `xskillscore` updates dependencies before we do
- unsure if `pearson_r` is dask compatible and efficient about it

**Comment by erogluorhan** [comment]
Thanks for exploring and asking these!

[xskillscore](https://github.com/xarray-contrib/xskillscore) seems like a lightweight interface through [accessors](https://docs.xarray.dev/en/stable/internals/extending-xarray.html) on top of Xarray like many other [xarray-contrib](https://github.com/xarray-contrib). It makes Xarray Dataset(or Array) look like it has directly the functions (correlation and others in this case) itself. That said, there won't be a big issue with having this dependency added.

> unsure if pearson_r is dask compatible and efficient about it

Because of the above fact (extends Xarray through accessors), it should be Dask-compatible.

> pearson_r doesn't have support for numpy.ndarray

Even though its function signature does not support numpy.ndarray directly (this is likely because this is extending Xarray), numpy.ndarray support is technically there as Xarray wraps up Numpy arrays (if not Dask Arrays in case of chunked). Such explicit support could be added to our function signature and can be easily wrapped up inside.

Yo make a decision, please investigate if this is an experimental package for now, or if the implementations are valdiated. We can them discuss further.

**Comment by hCraker** [comment]
@erogluorhan
> To make a decision though, please investigate if this is an experimental package for now, or if the implementations are valdiated. We can them discuss further.

Their repo follows all of the development standards (unit tests, code coverage, CI tests) so I'm confident that the implementations have been validated. The only concern is that no contributions have been made in the last month, and the repo is very quiet. I have reached out to the developers to see what the status of the package is (active dev or maintenance) in a [discussion post](https://github.com/xarray-contrib/xskillscore/discussions/394) on their repo.

**Comment by hCraker** [comment]
xskillscore is being maintained but is allowing contributions as they come in. @erogluorhan and I have settled on adding xskillscore as a dependency, wrapping `pearson_r` in geocat-comp, and working to improve performance of `pearson_r` in the future. This way we can get the function incorporated into comp asap.
