### ISSUE TITLE
Should we keep listing dependencies under Installation docs?

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-comp#267]
There is a section named "Required dependencies for building and testing GeoCAT-comp" in `installation.rst`. 

It is probably helpful for the reader, but it requires the developers to always make sure the list is up-to-date with the actual dependencies that are listed in `environment.yml`, `requirements.txt`, or conda recipes. 

Should we consider reemoving that section or linking the reader to one of the above files?

**Comment by dcherian** [comment]
It's useful to list out if you have optional dependencies for specific features.

**Comment by hCraker** [comment]
@dcherian @erogluorhan Currently, `environment.yml` contains comments specifying which dependencies are for tests only. We could have a list on the website that is just the printed out `environment.yml` file as it is.

If we'd rather have `environment.yml` be the leanest possible environment, we could remove the testing only packages and then list the optional/test dependencies on the website manually and print out the contents of `environment.yml`.

Which approaches do you all think would be easiest to maintain? I favor the second approach since few users will ever need or want to run the tests.

**Comment by erogluorhan** [comment]
> 
> Which approaches do you all think would be easiest to maintain? I favor the second approach since few users will ever need or want to run the tests.

Even though this issue was completed with PR #293 , I notice I missed @hCraker 's comments and question and would like to answer now:

> If we'd rather have `environment.yml` be the leanest possible environment, we could remove the testing only packages and then list the optional/test dependencies on the website manually and print out the contents of `environment.yml`.

I wouldn't recommend removal of testing only packages because `environment.yml` is the leanest possible environment to get a developer's local environment configured not only for implementation but also for testing. That said, the way PR #293 made the things is the best for development and documenting purposes.
