### ISSUE TITLE
AttributeError: module 'geocat.comp' has no attribute 'dpres_plevel'

### ISSUE THREAD

**Issue by appopson** [NCAR/geocat-comp#282]
**Describe the bug**
Dear all,
I installed geocat.com  and geocat.f2py using **pip3**. 
I imported  geocat.comp

The command I am using is **dp = geocat.comp.dpres_plevel(plev, psfc, ptop)**
I will like to use the geocat.comp.dpres_plevel. 

I am having this error 

**AttributeError: module 'geocat.comp' has no attribute 'dpres_plevel'**

**Comment by anissa111** [comment]
Hi @appopson, thank you so much for reaching out!

I think I know what's going on with your code. We're experiencing a bug right now (see #212) where functions under our geocat-f2py repo are not being properly brought into the geocat.comp namespace when installed with pip.

Here is a [list of the functions](https://geocat-comp.readthedocs.io/en/latest/user_api/index.html#geocat-comp-routines-from-geocat-f2py) that are geocat-f2py functions that this issue is currently affecting.

To fix your issue, I would suggest installing geocat-comp with conda if possible.

**Comment by anissa111** [comment]
I'm going to go ahead and close this issue. Feel free to re-open if you are still experiencing issues
