### ISSUE TITLE
contour colors in linint2 example looks wrong

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#35]
The two figures in the linint2 example here:

https://geocat-comp.readthedocs.io/en/latest/examples.html

disagree more than expected. The first figure shows the original data. The second shows data resulting from interpolation with linint2. The colors used in the regridded data figure appear shifted up by one level in the color map. 

Reported by: rashidcomsis@gmail.com

**Comment by abrammer** [comment]
Digging around the docs and progress here and noticed this. 

The two plots are called independently so dynamically create their own color scales.  The colorbar is only relevant for the second plot here.  

Explicitly pass limits and extend options to make sure each plot is using the same color scale:
`vmin=-30, vmax=30, levels=16, extend="neither", `

You could also use the `xarray.DataArray.plot.contourf` functionality instead of creating the lat,lon mesh grid, though that forces some extra plotting options. 
e.g.:
```
plot_options = dict(transform=projection, cmap=cm.jet, vmin=-30, vmax=30, levels=16, extend='neither', add_colorbar=False, xtitle='')
for i, ax in enumerate(axgr):
    ax.coastlines()
    ...
    ax.yaxis.set_major_formatter(lat_formatter)

    # Plot contours for both the subplots
    if( i==0 ):
        sst.plot.contourf(ax=ax,**plot_options)
        ax.set_title('Original Grid', fontsize=14, fontweight='bold')
    else:
        p=newsst.plot.contourf(ax=ax,**plot_options)
        ax.set_title('ReGrid - linint2', fontsize=14, fontweight='bold')
    ax.xaxis.label.set_visible(False)
    ax.yaxis.label.set_visible(False)
```

**Comment by abb58** [comment]
Thanks @abrammer ! That really did the trick. 
![linint2](https://user-images.githubusercontent.com/9905141/66231872-c378a700-e6a4-11e9-9e90-1f1914c97762.png)
