### ISSUE TITLE
Namespaces for function categories

### ISSUE THREAD

**Issue by khallock** [NCAR/geocat-comp#37]
Continuing discussion from #32.

> May be we could group the functionalities; For example, grid related functionalities goes into `geocat.comp.grid`, Interpolation stuff goes in `geocat.comp.interpolation`, eof functionality in `geocat.comp.eof`, and so on.

_Originally posted by @maboualidev in https://github.com/NCAR/geocat-comp/pull/32#pullrequestreview-302652115_

>There is certainly potential for using namespaces under `geocat.comp`, but I'd be concerned about creating excessive namespaces -- `geocat.comp.eof.eofunc()` is clear but not concise. If we're going to go down that road, I think we may want to consider ditching the `comp` namespace and create the `eof` namespace directly on `geocat`: `geocat.eof.eofunc()`.
>
>Note that the package as a whole would still be called "GeoCAT-comp", we would just be changing the `import geocat.???` statements.

_Originally posted by @khallock in https://github.com/NCAR/geocat-comp/pull/32#issuecomment-543397908_

**Comment by jinqj** [comment]
Hello,

My name is Qinjian Jin and have used NCL for about 10 years. I switched to python a half year ago but switched back to NCL several weeks ago. Because I have an on-going project that needs to be done in a limited time, and it takes longer than a half year to completely transfer to python from NCL without a python version of most of NCL computational functions. The geocat project is the right thing I am looking for. A big "Thank you" to you guys.

Related to the discussion of the namespace, I prefer the idea of "geocat.eof.eofunc()" to "geocat.comp.eof.eofunc()" just because the former one is more concise. 

BTW, I also wrote some NCL functions for my own purpose. I hope I could contribute to this project in the future.

**Comment by clyne** [comment]
Hi Qinjian,

Thanks for your input on this! We love hearing from the user community. Glad to hear that you support the direction we are going. Regarding contributions: we're still working on putting infrastructure in place to facilitate community contributions, and look forward to seeing yours.

cheers

**Comment by erogluorhan** [comment]
@pilotchute @anissa111 @michaelavs I think this is an important discussion, and we need to come up with a decision/solution for this in the newer releases. Thoughts?

**Comment by pilotchute** [comment]
My understanding is that we will try to bring all the functions from within the various modules all the way up to the geocat.comp namespace via the __init_.py imports. 
Thus to use the example from ealier in this thread: `geocat.comp.eofunc()`.

**Comment by anissa111** [comment]
I am okay with either approach, but I prefer the `geocat.eof.eofunc()` approach. Would out namespace structure also cover function families, like the fire index functions? In that case, expanding the namespace to something like `geocat.comp.fireindex.something()` might become a little unwieldy, since the functions would need to be classified under the computational umbrella of geocat.

**Comment by erogluorhan** [comment]
> My understanding is that we will try to bring all the functions from within the various modules all the way up to the geocat.comp namespace via the __init_.py imports.
> Thus to use the example from ealier in this thread: `geocat.comp.eofunc()`.

This issue says various modules should be grouped into categorized namespaces instead of importing them directly under `geocat.comp` as we have done so far. In other words, this suggested namespacing resembles more of a `matplotlib` or other big package namespacing. For example:

`linint2` would be under such a namespace: `geocat.comp.interpolation.linint2` (instead of `geocat.comp.linint2`)
`rcm2rgrid` would be under such a namespace: `geocat.comp.regridding.rcm2rgrid` (instead of `geocat.comp.rcm2rgrid`)

I would prefer such a namespace to help the end-user narrow down her search for a function of specific class in addition to having a more readable categorized namespace overall. It would also help NCL users map `geocat.comp` functions to NCL functions as in here:

https://www.ncl.ucar.edu/Document/Functions/index.shtml

In the long run, having similar namespaces under `geocat.comp` would be of high use I believe.

**Comment by erogluorhan** [comment]
Closing this issue for now, with the decision of keeping the current namespace attitude as is. It may be revisited in the future if needed.
