### ISSUE TITLE
Remove Xarray Private API and remove pinning

### ISSUE THREAD

**Issue by pilotchute** [NCAR/geocat-comp#381]
**Describe the bug**
Xarray 2023.03.0 breaks tests due to a call on [line 1818 of xarray/core/common.py](https://github.com/pydata/xarray/blob/1e361ccb9123fe25acfd9e3364c911c1eec7d9db/xarray/core/common.py#L1818)

**To Reproduce**
run tests

**Expected behavior**
no error

**Screenshots**
[Failing test run](https://github.com/NCAR/geocat-comp/actions/runs/4503455909/jobs/7926663488)
**OS:**
Both MacOS and Ubuntu

**Environment**
n/a

**Comment by anissa111** [comment]
This seems relevant: https://github.com/pydata/xarray/issues/7645

**Comment by dcherian** [comment]
> xr.core.common.contains_cftime_datetimes(d_arr)

This is private API, you should vendor it though the current version isn't the most friendly for vendoring. So perhaps reimplement it.

Also I recommend updating your `upstream-dev-ci` (e.g. https://github.com/corteva/rioxarray/issues/654)

**Comment by cyschneck** [comment]
Part of this issue appears in [02-more_advanced_functionality](https://github.com/NCAR/geocat-tutorials/blob/main/notebooks/geocat-comp/02-more_advanced_functionality.ipynb) and prevents graphs from being generated
```python
# Minimal Example:
from geocat.comp import climatology_average
import xarray as xr
import geocat.datafiles as gdf

nc_file = gdf.get('netcdf_files/atm.20C.hourly6-1990-1995-TS.nc')
ds = xr.open_dataset(nc_file)
ds = ds.isel(member_id=0)  # select one model from the ensemble

temp = ds.TS
monthly_temp = climatology_average(temp, freq='month')
```
Throws: `AttributeError: 'DataArray' object has no attribute '_data'`

The issue seems to come from `contains_cftime_datetimes` [no longer accepts DataArrays](https://github.com/pydata/xarray/issues/7966#issuecomment-1627677281). So now it expects `xarray.Variable`

For now, while running locally by changing `xr.core.common.contains_cftime_datetimes(d_arr)` to `xr.core.common.contains_cftime_datetimes(d_arr.variable)` fixes the error and can now generate graphs in the geocat-tutorials

[Until there is a public API](https://github.com/pydata/xarray/issues/7645#issuecomment-1475557707) this can be change in [/home/user/miniconda3/envs/geocat-tutorials/lib/python3.10/site-packages/geocat/comp/climatologies.py](https://github.com/NCAR/geocat-comp/blob/2e7c1f5fe292147a63249844b0363f962aa32098/geocat/comp/climatologies.py#L16) on conda to run the tutorial
```
def _contains_datetime_like_objects(d_arr):
    """Check if a variable contains datetime like objects (either
    np.datetime64, or cftime.datetime)"""
    return np.issubdtype(
        d_arr.dtype,
        np.datetime64) or xr.core.common.contains_cftime_datetimes(d_arr.variable)
```

**Comment by cyschneck** [comment]
Currently, an open issue on geocat-comp. Can get around the error by setting `xarray<=2023.02.0`

[A more general solution](https://github.com/pydata/xarray/issues/7645#issuecomment-1475150683)

```data = encode_cf_variable(out_data).values.astype(numpy_dtype)```
with
```data = encode_cf_variable(out_data.variable).values.astype(numpy_dtype)```
