### ISSUE TITLE
specx

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-comp#43]
Port the NCL specx family of functions to Python, which include: specx_anal, specx_ci, and specxy_anal. These functions spectra of a series.

**Comment by mariajmolina** [comment]
Hello @clyne and @erogluorhan -- Has there been an update on this? I am asking because I am currently working on trying to replicate the spectral analysis I get from [spec_1.ncl](https://www.ncl.ucar.edu/Applications/Scripts/spec_1.ncl) using pure python, but am not able to yet. I think its because I don't fully understand the steps talked about [here](https://sites.google.com/site/earthsciencedataanalysis/software-tools-list/chapters/Data-Analysis-Discussions/ncl-discussion/powerspectrum), nor am I sure if all these steps occur in the [specx_anal function](https://www.ncl.ucar.edu/Document/Functions/Built-in/specx_anal.shtml). Specifically, I am not sure how steps f and g are followed (e.g., how many units are used for the running average?). Any guidance would be greatly appreciated! Thank you!

**Comment by erogluorhan** [comment]
Hi @mariajmolina , thanks a lot for reaching out! There has not been an update yet, though, we could work on wrapping this function up in our GeoCAT-comp stack. The fastest way to do this is likely to wrap up the Fortran code in Python with the help of Numpy.f2py. I see that you are trying to come up with a pure Python implementation instead. Please let us know your thoughts on either wrapping up Fortran code or implementing pure Python algorithm. If you're fine with the former, the GeoCAT team would try to prioritize this, as soon as the team agenda permits. Otherwise, we could even collaborate to implement the latter together.

**Comment by mariajmolina** [comment]
Thank you so much for your response @erogluorhan -- I appreciate you explaining the several potential ways forward. I would be okay with wrapping the Fortran code in Python, but I would prefer the latter option (pure python) so that I could much more easily make modifications if needed and fully understand the series of calculations. I would be very happy to collaborate with you on a python implementation! Please let me know how it would be best to collaborate on this.

**Comment by pilotchute** [comment]
Overarching: https://github.com/NCAR/geocat-comp/issues/124

**Comment by anissa111** [comment]
Closing this issue as duplicated in #124
