### ISSUE TITLE
[💡]: Xarray Accessors 

### ISSUE THREAD

**Issue by philipc2** [NCAR/geocat-comp#641]
### Describe the functionality you are requesting, linking any relevant usage or previous implementations in the python ecosystem or otherwise.

The majority of functions provided by `geocat-comp` support `xr.Dataset` or `xr.DataArray` objects as inputs. While having a procedural approach is familiar for users coming from `ncl`, it may be worth considering also supporting accessors directly linked to Xarray objects.

`xcDat` does this pretty elegantly (see [here](https://xcdat.readthedocs.io/en/latest/api.html#accessors)) 

`hvPlot` attaches it's accessors to different objects through important specified modules

```Python
# attaches the `hvplot` accessor to xarray objects

import hvplot.xarray

xrda.hvplot()
```

For `geocat-comp`, an `hvplot` inspired approach could look something like the following:

```Python
import xarray as xr

# this would attach "geocat" objects to xarray data structures 
import geocat.comp.xarray

xrds = ...

# one possible syntax
xrds['t2m'].geocat.gradient()

# another possible syntax 
xrds['t2m'].geocat.comp.gradient()

# equivalent to 
gc.gradient(xrds['t2m'])
```

### Is this a request for functionality that was previously in NCL?

No

**Comment by anissa111** [comment]
Thanks for the thought, Philip! 

Could you explain what benefits we'd get by adding xarray accessors?

**Comment by philipc2** [comment]
> Thanks for the thought, Philip!
> 
> Could you explain what benefits we'd get by adding xarray accessors?

Here's a blurb from Xarray's documentation on accessors:

> The intent here is that libraries that extend xarray could add such an accessor to implement subclass specific functionality rather than using actual subclasses or patching in a large number of domain specific methods. For further reading on ways to write new accessors and the philosophy behind the approach

While `geocat-comp` isn't intend ended as a xarray extension, having accessors as an option for users could make it more intuitive to call methods and allow for better function chaining with Xarray methods. 

```Python
# assuming a '.geocat'`  accessor 
import geocat.comp.xarray 

xrds = ...

# with accessor 
xrds['var'].geocat.gradient().mean().plot()

# without accessor 
gc.gradient(xrds['var'].gradient()).mean().plot()
```

**Comment by anissa111** [comment]
> An analogue would be the way NumPy handles a lot of functionality. You can call np.mean(arr) or arr.mean(), with both being valid approaches.

I think that this is meaningfully different than geocat-comp functionality, because numpy provides both objects (numpy arrays) and functions that act on those objects, while geocat-comp does not provide a data object, just functions that act on data objects.

While users could choose to use either method if we did implement something like you're describing, I'm not seeing any additional actual benefit that this would provide other than an additional way to call our functionality while adding additional code to maintain and a need to create and maintain additional documentation for us.

**Comment by philipc2** [comment]
> > An analogue would be the way NumPy handles a lot of functionality. You can call np.mean(arr) or arr.mean(), with both being valid approaches.
> 
> I think that this is meaningfully different than geocat-comp functionality, because numpy provides both objects (numpy arrays) and functions that act on those objects, while geocat-comp does not provide a data object, just functions that act on data objects.
> 
> While users could choose to use either method if we did implement something like you're describing, I'm not seeing any additional actual benefit that this would provide other than an additional way to call our functionality while adding additional code to maintain and a need to create and maintain additional documentation for us.

That's understandable. Feel free to close this issue if this isn't something of interest.

**Comment by erogluorhan** [comment]
This is exactly what I have been thinking of for a while! A number of benefits I can immediately think of with it:

- Xarray objects are the main data structures all of the geocat-comp functions already consume, so implementation-wise this could be a low hanging fruit to achieve and maintain later
- A lot of people in geosciences are very well aware of the Xarray syntax and appreciate new tools that align with that same syntax, e.g.. lightweight Xarray extensions
   - This could further help our community outreach efforts as well as Pangeo engagement
- Documentation can be handled in a way that we can advertise this from a central point (somewhere in the home page and beginning of the documentation for instance) rather than having individual doc entries for each accessor. This could help reduce documentation overhead
