### ISSUE TITLE
Functions to calculate Skew-T parameters

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-comp#89]
When plotting Skew-T data using NCL, the following information is calculated and added just under the figure title automatically:
-    Cape  -  Convective Available Potential Energy [J]
-    Pwat  -  Precipitable Water [cm]
-    Shox  -  Showalter Index (stability)
-    Plcl  -  Pressure of the lifting condensation level [hPa]
-    Tlcl  -  Temperature at the lifting condensation level [C]

The purpose of this issue is to create a function or set of functions using Python to calculate these values.

Some Related NCL functions:
[Precipitable Water](https://www.ncl.ucar.edu/Document/Functions/Built-in/prcwater_dp.shtml)
[Pressure of the LCL](https://www.ncl.ucar.edu/Document/Functions/Built-in/lclvl.shtml)
[Temperature of LCL](https://www.ncl.ucar.edu/Document/Functions/Contributed/tlcl_td_bolton.shtml)
Methods of computing CAPE [1](https://www.ncl.ucar.edu/Document/Functions/Built-in/wrf_cape_2d.shtml) and [2](https://www.ncl.ucar.edu/Document/Functions/Built-in/wrf_cape_3d.shtml)

**Comment by michaelavs** [comment]
@erogluorhan I see that you have assigned yourself to this issue, but I've been looking into the functions outlined and possible implementations this morning and wanted to run past you what I've seen so far. 

From what I have seen, all of these functions are currently in MetPy except for the Showalter Index, which I am currently working on a way to calculate this value using [MetPy calc functions](https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.html). With that being said, I wanted to know if using the MetPy functions would be the best route for this issue, or if we want to be building from the ground up and/or from NCL code. Further, if we used the MetPy code, would this issue remain in GeoCAT-comp, or would it be better to move it into something like GeoCAT-viz as it seems we may be further implementing the calculations into a plot-able subtitle text? 

Let me know what your thoughts are, and I can even open a PR or send over an email with the MetPy code I've been testing this morning if you want to look at it yourself.

**Comment by erogluorhan** [comment]
> @erogluorhan I see that you have assigned yourself to this issue, but I've been looking into the functions outlined and possible implementations this morning and wanted to run past you what I've seen so far.
> 
> From what I have seen, all of these functions are currently in MetPy except for the Showalter Index, which I am currently working on a way to calculate this value using [MetPy calc functions](https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.html). With that being said, I wanted to know if using the MetPy functions would be the best route for this issue, or if we want to be building from the ground up and/or from NCL code. Further, if we used the MetPy code, would this issue remain in GeoCAT-comp, or would it be better to move it into something like GeoCAT-viz as it seems we may be further implementing the calculations into a plot-able subtitle text?
> 
> Let me know what your thoughts are, and I can even open a PR or send over an email with the MetPy code I've been testing this morning if you want to look at it yourself.

Thanks a lot for looking into this and bringing up your findings! These are significant findings that help determine Geocat-comp roadmap. 

So, I agree that the only missing index in MetPy looks to be "show (Showalter Index)". Please also note that `metpy.calc.lifted_index()` looks similar to "shox" but differs with its use of initial location of the lifted parcel. It is possible that showalter index could be added to MetPy and in that case, calling all of these indices from metpy calculation would be straightforward. 

However today, for the GeoCAT user's convenience, we could add a `skewt_params` function into GeoCAT-comp, as you already did in PR #96 , that simple calls MetPy calculations for all of the indices except "shox". It could manually compute "shox" so that GeoCAT-comp provides a contribution to the community. Such a function would return all of these indices at once as output values. You can see my further findings and implementation relate comments in PR #96 conversation.
