### ISSUE TITLE
NCL: Principal Oscillation Pattern (POP) Analysis ?

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [NCAR/geocat-comp#98]
Aloha NCAR GEOCAT folks! First, thanks for these important efforts to renew the NCL legacy.

Apologies for a possibly ignorant question about the work plan for geocat-comp but are NCL tools like [Principal Oscillation Pattern (POP) Analysis](https://www.ncl.ucar.edu/Applications/prn_osc_pat.shtml) in scope? Planned?

Some of us have a selfish interest to be able to reproduce the "NCL: Principal Oscillation Pattern (POP) Analysis" but using python-based Xarray and also Dask for scale?

**Comment by pilotchute** [comment]
I'm not the authority on this, but here's my thoughts:
We would like to make sure that anything that could be done in NCL will be able to be done in GeoCAT unless some other python package already can. 

I personally don't know enough about POP to give a guess at how soon an implementation of it could be available in GeoCAT. From glancing at the underlying NCL code for it, it seems like there are no NCL specific fortran functions called, and that python's numpy package would have the needed linear algebra tools to perform the computation. (mostly eigenvectors it appears). 

Tomorrow is our team's hackday, and I'd be happy to chat with you about how the function works, and if we can replicate it in python.

**Comment by Thomas-Moore-Creative** [comment]
G'day from Tasmania, @pilotchute - thanks for your quick reply.  Missing my days in Boulder - all the best to Colorado and those FlatIrons!

Apologies that my query is a very ignorant one as I have never run any NCL or used POP analysis.  I was simply looking for python packages that, instead of EoFs, supported POP with some established legacy / confidence and was pointed at the NCL webpage.  Further questions on the Pangeo forum lead to a suggestion from others to ask your team if it's in the works?  

I understand it's a rather useful extension of spatio-temporal EoF analysis where we might simultaneously infer both the characteristic spatial patterns and timescales of a timeseries.  I believe that others would value the effort on this but the query is fairly bold self-interest on my part.

**Comment by pilotchute** [comment]
The math behind principal component analysis' like EoFs and by extension POP, is well covered by numpy, so I'm sure there's a way. I just need to figure out what exactly POP does with the EoFs once computed. :)

**Comment by erogluorhan** [comment]
Hi Thomas,

Thank you very much for reaching out to us with your requests/inputs! We love hearing from the user community to help determine our roadmap. 

"NCL: Principal Oscillation Pattern (POP) Analysis" is a great analysis that is pretty much related to / similar with `eof` functions, as you already mentioned. What is nice to know is that it was also a user-provided analysis method back in the days, instead of being a native NCL function. 

I would like to first say that several `EOF` functions (e.g. eofunc, eofunc_ts, etc.) are already accessible from under `geocat.comp`. Though, I haven't seen any "legacy" code that is deddicated to pure "Principal Oscillation Pattern (POP) Analysis" .  That being said, a "Principal Oscillation Pattern (POP) Analysis" methodology could be implemented based on our existing EOFs.

Our development of such an analysis would be great since we are committed to address geoscience community's computational needs with our `geocat.comp`. We are still working on the highest priority native NCL functions' implementations, and we would be interested in looking at this POP analysis in the future.  

I also wonder if you would ever be interested in contributing with your own "Principal Oscillation Pattern (POP) Analysis" based on our existing EOFs (Even though you have used neither NCL nor POP analysis on your own).

Best

Orhan at GeoCAT

**Comment by Thomas-Moore-Creative** [comment]
Thanks @erogluorhan to you and your GeoCAT team.  It would be great to see POP reborn under GeoCAT.  If I do come up with anything of my own, based on GeoCAT, I'd be happy to contribute.
